modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "village_shop_system"
version = "${version}"
displayName = "Village Shop System"
authors = ""
description = '''

'''

[[dependencies.village_shop_system]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.village_shop_system]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.village_shop_system]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "village_shop_system.mixins.json"
